Eletrodomesticos_01/Models/Eletrodomestico.cs
namespace Eletrodomesticos_01.Models
{
    public abstract class Eletrodomestico
    {
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public double ConsumoEnergetico { get; set; }

        public abstract string ExibirDetalhes();
    }
}

Eletrodomesticos_01/Models/ErrorViewModel.cs
namespace Eletrodomesticos_01.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Eletrodomesticos_01/Models/Geladeira.cs
using System.Reflection;
using System.Text.RegularExpressions;

namespace Eletrodomesticos_01.Models
{
    public class Geladeira : Eletrodomestico
    {
        public int CapacidadeLitros { get; set; }
        public bool TemFreezer { get; set; }
        public override string ExibirDetalhes()
        {
            return $"Marca: {Marca}, Modelo: {Modelo}, Capacidade: {CapacidadeLitros}, Tem freezer: {(TemFreezer ? "Sim" : "Não")}";
        }
    }
}

Eletrodomesticos_01/Models/Televisao.cs
using System.Reflection;
using System.Text.RegularExpressions;

namespace Eletrodomesticos_01.Models
{
    public class Televisao : Eletrodomestico
    {
        public int TamanhoTela { get; set; }
        public bool EhSmart { get; set; }
        public override string ExibirDetalhes()
        {
            return $"Marca: {Marca}, Modelo: {Modelo}, Consumo: {ConsumoEnergetico}, Tela: {TamanhoTela}, Smart: {(EhSmart ? "Sim" : "Não")}";
        }
    }
}

Eletrodomesticos_01/Controllers/HomeController.cs
using Eletrodomesticos_01.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Eletrodomesticos_01.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Eletrodomesticos_01/Controllers/ListaEletrodomesticoController.cs
using Eletrodomesticos_01.Models;
using Microsoft.AspNetCore.Mvc;

namespace Eletrodomesticos_01.Controllers
{
    public class ListaEletrodomesticoController : Controller
    {
        public IActionResult Index()
        {
            List<Eletrodomestico> eletrodomesticos = new List<Eletrodomestico>
            {
                new Geladeira {Marca = "Eletrolux", Modelo = "Frost Free", ConsumoEnergetico = 5, CapacidadeLitros = 410, TemFreezer = true },
                new Televisao {Marca = "TCL", Modelo = "C655", ConsumoEnergetico = 10, EhSmart = true, TamanhoTela = 50 },
                new Televisao {Marca = "Philips", Modelo = "7019", ConsumoEnergetico = 15, EhSmart = true, TamanhoTela = 50 }

            };

            return View(eletrodomesticos);
        }
    }
}

Eletrodomesticos_01/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Eletrodomesticos_01/Views/ListaEletrodomestico/Index.cshtml
@model List<Eletrodomestico>
<h1>Lista de dispositivos eletronicos</h1>

<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Marca</th>
            <th>Modelo</th>
            <th>Consumo Energético</th>
            <th>Detalhes</th>



        </tr>
    </thead>
    <tbody>
        @foreach (var dispositivo in Model)
        {
            <tr>
                <td>@dispositivo.Marca</td>
                <td>@dispositivo.Modelo</td>
                <td>@dispositivo.ConsumoEnergetico</td>
                <td>
                    @if (dispositivo is Televisao)
                    {
                        <strong>TELA:</strong> @(((Televisao)dispositivo).TamanhoTela)  <br />
                        <strong>SMART:</strong> @(((Televisao)dispositivo).EhSmart ? "Sim" : "Não")
                    }
                    else if (dispositivo is Geladeira)
                    {
                        <strong>FREEZER</strong> @(((Geladeira)dispositivo).TemFreezer ? "Sim" : "Não") <br />
                        <strong>Capacidade (L):</strong> @(((Geladeira)dispositivo).CapacidadeLitros)



                    }
                </td>
            </tr>
        }
    </tbody>
</table>

Eletrodomesticos_01/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Eletrodomesticos_01</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Eletrodomesticos_01.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Eletrodomesticos_01</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ListaEletrodomestico" asp-action="Index">Eletrodomesticos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Eletrodomesticos_01 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>